.TH random::rand8 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
random::rand8 \- Generate a 8-bits random number
.SH SYNOPSIS
.B random::rand8
.SH DESCRIPTION
Generate a 8-bits random number.
.br
Values returned are in the range [0, 255] inclusive.
.SH "SEE ALSO"
random::rand16(1), random::rand24(1), random::rand32(1)
