.TH system::patch_create 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
system::patch_create \- Create a Unix patch

.SH SYNOPSIS
.B system::patch_create
.IR oldfile
.IR newfile
.IR output

.SH DESCRIPTION
Compare \fBoldfile\fR and \fBnewfile\fR, and create a patch from the difference into
\fBoutput\fR.

.SH EXAMPLES
system::patch_create main.c main_new.c main.patch

.SH "SEE ALSO"
system::patch_apply(1), system::patch_revert(1)
