.TH strings::trim 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
strings::trim \- Remove blanks at the beginning and end of a string

.SH SYNOPSIS
.B strings::trim
.IR string

.SH DESCRIPTION
Remove blanks at the beginning and end of a string.
.br
The initial string is not modified.

.SH "SEE ALSO"
strings::ltrim(1), strings::rtrim(1)

