.TH network::mcast_recv 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
network::mcast_recv \- UDP Multicast Receiver and recorder

.SH SYNOPSIS
.B network::mcast_recv
.IR [options]
.IR mcast_addr:port

.SH DESCRIPTION
Receive UDP multicast packets on the network.
.br
Options:
.RS
-o|--output : a filename for recording incoming multicast traffic
.br
-i|--iface  : listen on this particular interface

.SH EXAMPLES
# record packets from the network
.br
network::mcast_recv -o market_data.dat 224.0.0.1:5000

.SH "SEE ALSO"
network::mcast_pub(1)

