.TH system::patch_apply 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
system::patch_apply \- Apply a Unix patch to a file

.SH SYNOPSIS
.B system::patch_apply
.IR file
.IR patch

.SH DESCRIPTION
Apply the patch in \fBpatch\fR to \fBfile\fR.

.SH EXAMPLES
system::patch_apply main.c main.patch

.SH "SEE ALSO"
system::patch_create(1), system::patch_revert(1)
