.TH docker::image_name 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
docker::image_name \- retrieve the full name of an image
.SH SYNOPSIS
.B docker::image_name
.IR image_id
.SH DESCRIPTION
Retrieve the name associated with an image.
.SH EXAMPLES
docker::image_name fd8db90652e6
.SH "SEE ALSO"
docker::image_tag(1), docker::image_version(1), docker::image_size(1)
