.TH docker::get_name 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
docker::get_name \- retrieve the name of a container
.SH SYNOPSIS
.B docker::get_name
.IR container_id
.SH DESCRIPTION
Retrieve the name of a container from the \fBcontainer ID\fR.
.SH EXAMPLES
docker::get_name b2a448b6a7c9
.SH "SEE ALSO"
docker::get_id(1)