.TH git::is_working_tree 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
git::is_working_tree \- Check if we are inside a GIT working tree
.SH SYNOPSIS
.B git::is_working_tree
.SH DESCRIPTION
Check if we are inside a GIT working tree.
.br
Returns \fBTrue\fR if we are in a working GIT tree, \fBFalse\fR otherwise.
