.TH logger::info 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
logger::info \- Print an info message
.SH SYNOPSIS
.B logger::info
.IR message
.SH DESCRIPTION
Print an info message.
.SH EXAMPLES
logger::info "Starting application ..."
.SH "SEE ALSO"
logger::setLogLevel(1), logger::debug(1), logger::warning(1), logger::error(1), logger::critical(1)