.TH strings::ltrim 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
strings::ltrim \- Remove blanks at the beginning of a string

.SH SYNOPSIS
.B strings::ltrim
.IR string

.SH DESCRIPTION
Remove blanks at the beginning of a string.
.br
The initial string is not modified.

.SH "SEE ALSO"
strings::rtrim(1), strings::trim(1)

