.TH system::patch_revert 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
system::patch_revert \- Revert a Unix patch to a file

.SH SYNOPSIS
.B system::patch_revert
.IR file
.IR patch

.SH DESCRIPTION
Revert the patch in \fBpatch\fR applied to \fBfile\fR.

.SH EXAMPLES
system::patch_revert main.c main.patch

.SH "SEE ALSO"
system::patch_create(1), system::patch_apply(1)
