.TH strings::right 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
strings::right \- Extract count characters from the end of the string

.SH SYNOPSIS
.B strings::right
.IR count
.IR string

.SH DESCRIPTION
Extract \fBcount\R characters from the end of the string.
.br
The initial string is left unchanged.

.SH "SEE ALSO"
strings::left(1), strings::mid(1)

