.TH execute::true 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
execute::true \- function that always return true
.SH SYNOPSIS
.B execute::true
.SH DESCRIPTION
When executed, this function always returns true.
.SH EXAMPLES
[[ execute::true && something_executed ]]
.SH "SEE ALSO"
execute::wait_until(1), execute::false(1), execute::run_in(1)
