.TH strings::mid 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
strings::mid \- Extract count characters of the string from the position specified

.SH SYNOPSIS
.B strings::mid
.IR position
.IR count
.IR string

.SH DESCRIPTION
Extract \fBcount\fR characters of the string from the \fBposition\fR specified.
.br
The initial string is left unchanged.

.SH "SEE ALSO"
strings::left(1), strings::right(1)

