.TH system::file_compare 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
system::file_compare \- Compare two files

.SH SYNOPSIS
.B system::file_compare
.IR file1
.IR file2

.SH DESCRIPTION
Compare \fBfile1\fR and \fBfile2\fR, and return \fBTrue (0)\fR if they are identical,
\fBFalse (1)\fR otherwise.

.SH EXAMPLES
system::file_compare video1.mp4 video2.mp4
