.TH execute::false 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
execute::false \- function that always return false
.SH SYNOPSIS
.B execute::false
.SH DESCRIPTION
When executed, this function always returns false.
.SH EXAMPLES
[[ execute::false && something_not_executed ]]
.SH "SEE ALSO"
execute::wait_until(1), execute::true(1), execute::run_in(1)
