.TH docker:: 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
docker:: \- bash functions for docker management in scripts
.SH SYNOPSIS
.B docker::<function>
.IR arguments
.SH DESCRIPTION
bash functions to help managing docker containers and images in scripts.
.SH "SEE ALSO"
.PP
docker::log_path(1), docker::get_name(1), docker::get_id(1),
.br
docker::base_image(1), docker::base_image_short(1),
.br
docker::image_tag(1), docker::image_name(1), docker::image_version(1), docker::image_size(1)
