.TH git::local_dir 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
git::local_dir \- Return the absolute location of the current GIT local directory
.SH SYNOPSIS
.B git::local_dir
.SH DESCRIPTION
Return the absolute location of the current GIT local directory.
.SH "SEE ALSO"
git::repo_url(1), git::repo_name(1)