.TH format::size 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
format::size \- convert the size in Bytes in its Human Readable format
.SH SYNOPSIS
.B format::size
<size (in Bytes)>
.SH DESCRIPTION
Convert the size in Bytes in its Human Readable equivalent.
.br
Supported units are: B, KiB, MiB, GiB, TiB
.SH EXAMPLES
format::size 573768
