.TH docker::log_path 1 "June 2024" "1.0.0"
.SH NAME
docker::log_path \- retrieve the logpath of a container
.SH SYNOPSIS
.B docker::log_path
.IR container_id | container_name
.SH DESCRIPTION
Retrieve the path on the system where the log for this container is stored.
.SH EXAMPLES
docker::log_path b2a448b6a7c9
.br
docker::log_path magical_wand
