.TH random::rand24 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
random::rand24 \- Generate a 24-bits random number
.SH SYNOPSIS
.B random::rand24
.SH DESCRIPTION
Generate a 24-bits random number.
.br
Values returned are in the range [0, 16'777'215] inclusive.
.SH "SEE ALSO"
random::rand8(1), random::rand16(1), random::rand32(1)
