.TH stack::push 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
stack::push \- Add a new value on top of the stack

.SH SYNOPSIS
.B stack::push
.IR value

.SH DESCRIPTION
Add a new value on top of the stack.

.SH EXAMPLES
Push a new value on top of the stack
.br

.RS
# The stack before : [10]
.br
$ stack::push 42
.br
# The stack after  : [10 42]



.SH "SEE ALSO"
stack::pop(1), stack::dup(1), stack::swap(1), stack::top(1), stack::drop(1),
.br
stack::count(1), stack::print(1), stack::rotate(1), stack::clear(1)
