.TH strings::left 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
strings::left \- Extract count characters from the beginning of the string

.SH SYNOPSIS
.B strings::left
.IR count
.IR string

.SH DESCRIPTION
Extract \fBcount\R characters from the beginning of the string.
.br
The initial string is left unchanged.

.SH "SEE ALSO"
strings::right(1), strings::mid(1)

