.TH logger::error 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
logger::error \- Print an error message
.SH SYNOPSIS
.B logger::error
.IR message
.SH DESCRIPTION
Print an error message.
.SH EXAMPLES
logger::error "The file cannot be found on the system."
.SH "SEE ALSO"
logger::setLogLevel(1), logger::info(1), logger::warning(1), logger::debug(1), logger::critical(1)