.TH docker::image_id_short 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
docker::image_id_short \- retrieve the short SHA256 from the base image of a container
.SH SYNOPSIS
.B docker::image_id_short
.IR container_name | container_id
.SH DESCRIPTION
Retrieve the short SHA256 of the base image of a container.
.SH EXAMPLES
docker::image_id_short magical_wand
.br
docker::image_id_short b2a448b6a7c9
.SH "SEE ALSO"
docker::base_image(1)
