.TH config::ini 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
config::ini \- Retrieve the value of a specific key in the INI configuration file

.SH SYNOPSIS
.B config::ini
.IR [-s|--sections]
.IR [-k|--keys]
.IR <-f|--file
.IR filename>
.IR <key|section>

.SH DESCRIPTION
-s|--sections: print all available sections from the file.
               \fBsection\fR must be set to 'all'

.br
-k|--keys    : print all the available keys in a section.
               \fBsection\fR must be set to the corresponding section.

.br
-f|--file    : configuration file

.br
key          : 'section.key' to retrieve from the file


.SH EXAMPLES
# retrieve the database username in the credentials.ini file
.br
config::ini -f credentials.ini database.username
.br

.br
# print all available sections
.br
config::ini -s credentials.ini all

.SH "SEE ALSO"
config::toml(1), config::yaml(1)

