.TH kvstore::clean 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
kvstore::clean \- Clean the store from expired values

.SH SYNOPSIS
.B kvstore::clean

.SH DESCRIPTION
This function will clean the store from expired and old key/values.
.br
It's meant to be called periodically to maintain the store size to a minimum.

.SH "SEE ALSO"
kvstore::set(1), kvstore::get(1),
kvstore::del(1), kvstore::print(1)

