.TH network::mcast_pub 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
network::mcast_pub \- UDP Multicast Publisher and replay

.SH SYNOPSIS
.B network::mcast_pub
.IR [options]
.IR mcast_addr:port

.SH DESCRIPTION
Publish UDP multicast packets on the network.
.br
Options:
.RS
-i|--input : a filename (saved by network::mcast_recv) for replay
.br
-t|--ttl   : TTL for multicast packets (default: 1)
.br
-s|--sleep : Sleep time between send

.SH EXAMPLES
# replay packets from file
.br
network::mcast_pub -i market_data.dat 224.0.0.1:5000

.SH "SEE ALSO"
network::mcast_recv(1)

