.TH stack::print 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
stack::print \- Print the content of the stack

.SH SYNOPSIS
.B stack::print

.SH DESCRIPTION
This function prints the actual content of the stack.
It's mainly a debug tool to ensure previous operations were properly executed.

.SH EXAMPLES
Print the stack
.br

.RS
# the stack before : [10 20 30]
.br
$ stack::print     # will return 10 20 30
.br
# the stack after  : [10 20 30]

.SH "SEE ALSO"
stack::push(1), stack::pop(1), stack::dup(1), stack::top(1), stack::drop(1),
.br
stack::swap(1), stack::count(1), stack::rotate(1), stack::clear(1)
