.TH logger::setLogLevel 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
logger::setLogLevel \- Set the Log level for the library
.SH SYNOPSIS
.B logger::setLogLevel
.IR level
.SH DESCRIPTION
Set the Log level for the library.
.br
Available log level are:
.br
- \fBDEBUG\fR
.br
- \fBINFO\fR
.br
- \fBWARNING\fR
.br
- \fBERROR\fR
.br
- \fBCRITICAL\fR
.br
The default log level is \fBINFO\fR.
.SH EXAMPLES
logger::setLogLevel "WARNING"
.SH "SEE ALSO"
logger::debug(1), logger::info(1), logger::warning(1), logger::error(1), logger::critical(1)