.TH stack::swap 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
stack::swap \- Swap the top two values

.SH SYNOPSIS
.B stack::swap

.SH DESCRIPTION
This function swap the top two values.

.SH EXAMPLES
Swap the top value
.br

.RS
# the stack before : [10 20 30]
.br
$ stack::swap
.br
# the stack after  : [10 30 20]

.SH "SEE ALSO"
stack::push(1), stack::pop(1), stack::dup(1), stack::top(1), stack::drop(1),
.br
stack::count(1), stack::print(1), stack::rotate(1), stack::clear(1)
