.TH network::zero_connect 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
network::zero_connect \- Test if a port is opened on a host

.SH SYNOPSIS
.B network::zero_connect
.IR <host:port>

.SH DESCRIPTION
Open a TCP connection on \fBhost\fR at port \fBport\fR.
.br
Returns 0 if the port is opened, >0 otherwise.

.SH EXAMPLES
# test connection on distant host
.br
network::zero_connect coyote.acme.com:8000

.SH "SEE ALSO"
network::fake_server(1)

