.TH stack::dup 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
stack::dup \- Duplicate the top value

.SH SYNOPSIS
.B stack::dup

.SH DESCRIPTION
This function dupllicates the top value

.SH EXAMPLES
Duplicate the top value
.br

.RS
# the stack before : [10 20 30]
.br
$ stack::dup
.br
# the stack after  : [10 20 30 30]

.SH "SEE ALSO"
stack::push(1), stack::pop(1), stack::swap(1), stack::top(1), stack::drop(1),
.br
stack::count(1), stack::print(1), stack::rotate(1), stack::clear(1)
