.TH network::fake_server 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
network::fake_server \- Start an empty HTTP server to test connection

.SH SYNOPSIS
.B network::fake_server
.IR <TCP_port>

.SH DESCRIPTION
Start an empty HTTP server to test if a port is reachable/opened on the server.

.SH EXAMPLES
# start a HTTP server on port 8000
.br
network::fake_server 8000

.SH "SEE ALSO"
network::zero_connect(1)

