.TH random::rand32 1 "June 2024" "1.0.0" "BSFPE"
.SH NAME
random::rand32 \- Generate a 32-bits random number
.SH SYNOPSIS
.B random::rand32
.SH DESCRIPTION
Generate a 32-bits random number.
.br
Values returned are in the range [0, 4'294'967'295] inclusive.
.SH "SEE ALSO"
random::rand8(1), random::rand16(1), random::rand24(1)
