.TH stack::top 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
stack::top \- Retrieve the top value

.SH SYNOPSIS
.B stack::top

.SH DESCRIPTION
This function retrieves the top value from the stack, without removing it.

.SH EXAMPLES
Retrieves the top value.
.br

.RS
# the stack before : [10 20 30]
.br
$ stack::top     # will return 30
.br
# the stack after  : [10 20 30]

.SH "SEE ALSO"
stack::push(1), stack::pop(1), stack::dup(1), stack::swap(1),
stack::drop(1),
.br
stack::count(1), stack::print(1), stack::rotate(1), stack::clear(1)
