.TH system::cpu_count 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
system::cpu_count \- Retrieve the CPU count

.SH SYNOPSIS
.B system::cpu_count

.SH DESCRIPTION
Retrieve the CPU type as listed in \fB/proc/cpuinfo\fR.
.br
\fBWarning:\fR This command works only for system that supports /proc/cpuinfo file.

.SH "SEE ALSO"
system::cpu_type(1), system::cpu_flag(1)
