.TH stack::pop 1 "June 2024" "1.0.0" "BSFPE"

.SH NAME
stack::pop \- Get the top value and remove it

.SH SYNOPSIS
.B stack::pop

.SH DESCRIPTION
This function retrieves the value on the top and removes it from the stack.

.SH EXAMPLES
Returns the last value
.br

.RS
# The stack before : [10 20 30]
.br
$ stack::pop        # will output 30
.br
# The stack after  : [10 20]

.SH "SEE ALSO"
stack::push(1), stack::dup(1), stack::swap(1), stack::top(1), stack::drop(1),
.br
stack::count(1), stack::print(1), stack::rotate(1), stack::clear(1)
